### ISSUE TITLE
Question: Does alloydb-auth-proxy support the use of GKE workload identity

### ISSUE THREAD

**Issue by adamstrawson** [GoogleCloudPlatform/alloydb-auth-proxy#163]
## Question
Does `alloydb-auth-proxy` support the use of GKE workload identity when used with ServiceAccounts?

I'm in the process of setting up alloydb, and the plan is to run `alloydb-auth-proxy` as a sidecar container, similar to what we currently do with `cloud-sql-proxy`.

However, when using ServiceAccounts with workload identity, `alloydb-auth-proxy` fails to get the instance IP address. 

```
2022/11/02 17:55:53 [projects/{project}/locations/{region}/clusters/{cluster}/instances/{instance}] failed to connect to instance: failed to get instance IP address: Refresh error: failed to get instance metadata (instance URI = "{project}/{region}/{cluster}/{instance}"): Get "https://alloydb.googleapis.com/v1beta/projects/{project}/locations/{region}/clusters/{cluster}/instances/{instance}/connectionInfo": compute: Received 403 `Unable to generate access token; IAM returned 403 Forbidden: The caller does not have permission
```

No matter what role I include on the IAM Service Account, I can't get passed this error. 

Example Kubernetes resources below;

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloydb-proxy
  namespace: platform
  annotations:
    iam.gke.io/gcp-service-account: alloydb-proxy@{project}.iam.gserviceaccount.com
```

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloydb-proxy
  namespace: platform
spec:
  replicas: 1
    spec:
      serviceAccountName: alloydb-proxy
      containers:
      - name: alloydb-proxy
        image: gcr.io/alloydb-connectors/alloydb-auth-proxy:0.6.0
        ports:
        - containerPort: 5432
        command:
        - /alloydb-auth-proxy
        - {instance_uri}
```

The ServiceAccount `alloydb-proxy@{project}.iam.gserviceaccount.com` has the appropriate workload identity permissions (which we already use across the cluster and works fine, such as `cloud-sql-proxy`), originally the ServiceAccount had the role `role/alloydb.client`, but I've attempted a few variations around token creator etc, with no luck
