### ISSUE TITLE
Using auto-iam-auth make alloydb-auth-proxy try to connect to port 5433

### ISSUE THREAD

**Issue by sandangel** [GoogleCloudPlatform/alloydb-auth-proxy#731]
### Bug Description

I found my pod is restarting, in the logs it shows: 
```sh
failed to connect to instance: Dial error: failed to dial (instance URI = "<project>/us-central1/<cluster>/<instance>"): dial tcp 34.132.159.169:5433: connect: connection refused
```
Obviously my instances only expose port 5432, so this is failing. I'm not sure why it happens. But since this is failing, my pod was restarting as well because it was not able to connect to DB.

### Example code (or command)

```go
// paste your code here
```

### Steps to reproduce?

1. ?
2. ?
3. ?
...

### Environment

1. OS type and version:
2. AlloyDB Proxy version: 1.11.3-bookworm
3. Proxy invocation command 

```yaml
          args:
            - --auto-iam-authn
            - --public-ip
            - --address=0.0.0.0
            - --http-address=0.0.0.0
            - --health-check
            - --prometheus
            - --run-connection-test
            - --debug
            - --quitquitquit
            - --structured-logs
          env:
            - ALLOYDB_PROXY_INSTANCE_URI_0=projects/<my-project>/locations/us-central1/clusters/<cluster>/instances/<primary-instance>
            - ALLOYDB_PROXY_INSTANCE_URI_1=projects/<my-project>/locations/us-central1/clusters/<cluster>/instances/<read-pool>
```

:
