### ISSUE TITLE
error during shutdown: exporter is shutdown

### ISSUE THREAD

**Issue by a-martynovich** [GoogleCloudPlatform/alloydb-auth-proxy#776]
### Question

I'm using alloydb-auth-proxy as a sidecar (initContainer with restartPolicy: Always) in a k8s cronjob (GKE, Autopilot). 
The connection works fine, however when the cronjob is done the pod transitions into `Init:Error` state. because the init container outputs `error during shutdown: exporter is shutdown` and exits with code 1. 

### Code

```
apiVersion: batch/v1
kind: CronJob
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
        ...
          initContainers:
          - args:
            - --auto-iam-authn
            - --port=5432
            - --health-check
            - --exit-zero-sigterm
            - $(DATABASE_URI)
            image: gcr.io/alloydb-connectors/alloydb-auth-proxy
            restartPolicy: Always
            startupProbe:
              exec:
                command:
                - /alloydb-auth-proxy
                - wait
              failureThreshold: 3
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
          restartPolicy: Never
  schedule: 15 2 * * *
  startingDeadlineSeconds: 300
  ...
```

### Additional Details

Looking at the source code I figured this may be related to tracing or telemetry, but i never enabled them, and explicitly disabling them doesn't do anything. I also tried running the cronjob on different nodes and it didn't make any difference. However when I run the cronjob in a different k8s namespace it doesn't enter into `Init:Error` and completes successfully. What can cause this?
